services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PORT
        value: 8000



  - type: web
    name: frontend
    env: node
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    plan: free
