services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    repoPath: backend

  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: "yarn build"
    startCommand: "yarn start"
    repoPath: frontend
